package com.test.uni;

import java.util.Collection;

import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

import com.test.uni.impl.DefaultCSModule;
import com.test.uni.impl.DefaultLecturer;
import com.test.uni.impl.DefaultMathModule;
import com.test.uni.impl.DefaultModule;
import com.test.uni.impl.DefaultPerson;
import com.test.uni.impl.DefaultStudent;

//import edu.stanford.smi.protegex.owl.javacode.ProtegeJavaMapping;
//import edu.stanford.smi.protegex.owl.model.OWLClass;
//import edu.stanford.smi.protegex.owl.model.OWLOntology;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.<p>
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: UniversityFactory<br>
 * @version generated on Wed Sep 24 17:41:25 EDT 2014 by rbara012
 */
public class UniversityFactory implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public UniversityFactory(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public UniversityFactory(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
   public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#CSModule
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#CSModule", CSModule.class, DefaultCSModule.class);
    }

    /**
     * Creates an instance of type CSModule.  Modifies the underlying ontology.
     */
    public CSModule createCSModule(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_CSMODULE, DefaultCSModule.class);
    }

    /**
     * Gets an instance of type CSModule with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public CSModule getCSModule(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_CSMODULE, DefaultCSModule.class);
    }

    /**
     * Gets all instances of CSModule from the ontology.
     */
    public Collection<? extends CSModule> getAllCSModuleInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_CSMODULE, DefaultCSModule.class);
    }


    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#Lecturer
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#Lecturer", Lecturer.class, DefaultLecturer.class);
    }

    /**
     * Creates an instance of type Lecturer.  Modifies the underlying ontology.
     */
    public Lecturer createLecturer(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }

    /**
     * Gets an instance of type Lecturer with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Lecturer getLecturer(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }

    /**
     * Gets all instances of Lecturer from the ontology.
     */
    public Collection<? extends Lecturer> getAllLecturerInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_LECTURER, DefaultLecturer.class);
    }


    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#MathModule
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#MathModule", MathModule.class, DefaultMathModule.class);
    }

    /**
     * Creates an instance of type MathModule.  Modifies the underlying ontology.
     */
    public MathModule createMathModule(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_MATHMODULE, DefaultMathModule.class);
    }

    /**
     * Gets an instance of type MathModule with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public MathModule getMathModule(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_MATHMODULE, DefaultMathModule.class);
    }

    /**
     * Gets all instances of MathModule from the ontology.
     */
    public Collection<? extends MathModule> getAllMathModuleInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_MATHMODULE, DefaultMathModule.class);
    }


    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#Module
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#Module", Module.class, DefaultModule.class);
    }

    /**
     * Creates an instance of type Module.  Modifies the underlying ontology.
     */
    public Module createModule(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_MODULE, DefaultModule.class);
    }

    /**
     * Gets an instance of type Module with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Module getModule(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_MODULE, DefaultModule.class);
    }

    /**
     * Gets all instances of Module from the ontology.
     */
    public Collection<? extends Module> getAllModuleInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_MODULE, DefaultModule.class);
    }


    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#Person
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#Person", Person.class, DefaultPerson.class);
    }

    /**
     * Creates an instance of type Person.  Modifies the underlying ontology.
     */
    public Person createPerson(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets an instance of type Person with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Person getPerson(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets all instances of Person from the ontology.
     */
    public Collection<? extends Person> getAllPersonInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }


    /* ***************************************************
     * Class http://people.cis.fiu.edu/~rbaral/university.owl#Student
     */

    {
        javaMapping.add("http://people.cis.fiu.edu/~rbaral/university.owl#Student", Student.class, DefaultStudent.class);
    }

    /**
     * Creates an instance of type Student.  Modifies the underlying ontology.
     */
    public Student createStudent(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }

    /**
     * Gets an instance of type Student with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Student getStudent(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }

    /**
     * Gets all instances of Student from the ontology.
     */
    public Collection<? extends Student> getAllStudentInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_STUDENT, DefaultStudent.class);
    }

	@Override
	public Class<?> getJavaInterfaceFromOwlClass(
			org.semanticweb.owlapi.model.OWLClass arg0) {
		// TODO Auto-generated method stub
		return null;
	}


}
