package com.test.uni.impl;

import com.test.uni.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLecturer <br>
 * @version generated on Wed Sep 24 17:41:25 EDT 2014 by rbara012
 */
public class DefaultLecturer extends WrappedIndividualImpl implements Lecturer {

    public DefaultLecturer(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://people.cis.fiu.edu/~rbaral/university.owl#teaches
     */
     
    public Collection<? extends Module> getTeaches() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TEACHES,
                                               DefaultModule.class);
    }

    public boolean hasTeaches() {
	   return !getTeaches().isEmpty();
    }

    public void addTeaches(Module newTeaches) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TEACHES,
                                       newTeaches);
    }

    public void removeTeaches(Module oldTeaches) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TEACHES,
                                          oldTeaches);
    }


    /* ***************************************************
     * Data Property http://people.cis.fiu.edu/~rbaral/university.owl#first_name
     */
     
    public Collection<? extends String> getFirst_name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRST_NAME, String.class);
    }

    public boolean hasFirst_name() {
		return !getFirst_name().isEmpty();
    }

    public void addFirst_name(String newFirst_name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRST_NAME, newFirst_name);
    }

    public void removeFirst_name(String oldFirst_name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRST_NAME, oldFirst_name);
    }


    /* ***************************************************
     * Data Property http://people.cis.fiu.edu/~rbaral/university.owl#last_name
     */
     
    public Collection<? extends String> getLast_name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAST_NAME, String.class);
    }

    public boolean hasLast_name() {
		return !getLast_name().isEmpty();
    }

    public void addLast_name(String newLast_name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAST_NAME, newLast_name);
    }

    public void removeLast_name(String oldLast_name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LAST_NAME, oldLast_name);
    }


    /* ***************************************************
     * Data Property http://people.cis.fiu.edu/~rbaral/university.owl#staff_id
     */
     
    public Collection<? extends Integer> getStaff_id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STAFF_ID, Integer.class);
    }

    public boolean hasStaff_id() {
		return !getStaff_id().isEmpty();
    }

    public void addStaff_id(Integer newStaff_id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STAFF_ID, newStaff_id);
    }

    public void removeStaff_id(Integer oldStaff_id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STAFF_ID, oldStaff_id);
    }


}
