package com.test.uni.impl;

import com.test.uni.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCSModule <br>
 * @version generated on Wed Sep 24 17:41:25 EDT 2014 by rbara012
 */
public class DefaultCSModule extends WrappedIndividualImpl implements CSModule {

    public DefaultCSModule(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
